"""I dati di registrazione delle varianti (copiati da ipotesi.md), usati da run.py per il log."""
import varianti as V

CRITERIO = ("batte nettamente la (a) e la (b) con contro_baseline (t oltre la soglia di Student) "
            "e R medio dopo i costi > 0 in costruzione")

FONTI = {
    "I-01": "Moskowitz, Ooi, Pedersen, 'Time Series Momentum', Journal of Financial Economics, maggio 2012; "
            "Liu, Tsyvinski, 'Risks and Returns of Cryptocurrency', NBER WP 24877, agosto 2018",
    "I-02": "Curtis M. Faith, 'Way of the Turtle', McGraw-Hill, 2007",
    "I-03": "Lehmann, 'Fads, Martingales, and Market Efficiency', QJE, febbraio 1990; Nagel, 'Evaporating Liquidity', RFS, luglio 2012",
    "I-04": "Schmeling, Schrimpf, Todorov, 'Crypto Carry', BIS Working Papers 1087, aprile 2023",
    "I-05": "Caporale, Plastun, 'The day of the week effect in the cryptocurrency market', Finance Research Letters, dicembre 2019; "
            "Aharon, Qadan, 'Bitcoin and the day-of-the-week effect', Finance Research Letters, dicembre 2019",
    "I-06": "Larry Williams, 'Long-Term Secrets to Short-Term Trading', Wiley, 1999",
    "I-07": "Larry Connors, Cesar Alvarez, 'Short Term Trading Strategies That Work', TradingMarkets, 2008",
    "I-08": "Lo, MacKinlay, 'When Are Contrarian Profits Due to Stock Market Overreaction?', RFS, 1990; "
            "Mohamad, Sifat, Shariff, 'Lead-Lag relationship between Bitcoin and Ethereum', RIBAF 50, 2019",
    "I-09": "John Bollinger, 'Bollinger on Bollinger Bands', McGraw-Hill, 2001",
    "I-11": "Shen, Urquhart, Wang, 'Bitcoin intraday time-series momentum', Financial Review 57(2), maggio 2022",
    "I-12": "Moreira, Muir, 'Volatility-Managed Portfolios', Journal of Finance 72(4), agosto 2017",
    "I-13": "Brock, Lakonishok, LeBaron, 'Simple Technical Trading Rules and the Stochastic Properties of Stock Returns', "
            "Journal of Finance, dicembre 1992; Hudson, Urquhart, 'Technical trading and cryptocurrencies', Annals of OR, 2021",
    "I-14": "Campbell, Grossman, Wang, 'Trading Volume and Serial Correlation in Stock Returns', QJE 108(4), novembre 1993",
    "I-15": "Carol L. Osler, 'Currency Orders and Exchange Rate Dynamics: An Explanation for the Predictive Success of "
            "Technical Analysis', Journal of Finance 58(5), ottobre 2003; Osler, 'Stop-loss orders and price cascades in "
            "currency markets', Journal of International Money and Finance 24(2), 2005",
    "I-10": "He, Manela, Ross, von Wachter, 'Fundamentals of Perpetual Futures', arXiv 2212.06888, dicembre 2022",
}

# id -> (idea, costruttore, meccanismo, parametri, previsione (r_min, r_max, testo))
VARIANTI = {
    "FTMUSDT-001": ("I-01", lambda: V.i01("FTMUSDT-001", "long"),
                    "momento di 2 settimane: dopo 14 giorni in rialzo il rialzo continua",
                    {"condizione": "close/close(-14) - 1 > 0", "stop": "2,5 ATR(14)", "target": None, "uscita": "a tempo dopo 5 barre"},
                    (-0.10, 0.20)),
    "FTMUSDT-002": ("I-01", lambda: V.i01("FTMUSDT-002", "short"),
                    "momento di 2 settimane: dopo 14 giorni in ribasso il ribasso continua",
                    {"condizione": "close/close(-14) - 1 < 0", "stop": "2,5 ATR(14)", "target": None, "uscita": "a tempo dopo 5 barre"},
                    (-0.10, 0.20)),
    "FTMUSDT-003": ("I-02", lambda: V.i02("FTMUSDT-003", "long"),
                    "rottura del massimo di 20 barre: gli ordini oltre il range spingono la continuazione",
                    {"condizione": "close > max(high 20 barre precedenti)", "stop": "2 ATR(20)", "target": None,
                     "uscita": "close < min(low 10 barre precedenti)"},
                    (-0.15, 0.15)),
    "FTMUSDT-004": ("I-02", lambda: V.i02("FTMUSDT-004", "short"),
                    "rottura del minimo di 20 barre: gli ordini oltre il range spingono la continuazione",
                    {"condizione": "close < min(low 20 barre precedenti)", "stop": "2 ATR(20)", "target": None,
                     "uscita": "close > max(high 10 barre precedenti)"},
                    (-0.15, 0.15)),
    "FTMUSDT-005": ("I-03", lambda: V.i03("FTMUSDT-005", "long"),
                    "ritorno dopo un ribasso estremo di 3 ore: chi offre liquidita' a venditori forzati e' pagato",
                    {"condizione": "z(3 ore) < -3, dev. std su 720 barre", "stop": "2 ATR(24)", "target": None, "uscita": "a tempo dopo 6 barre"},
                    (-0.10, 0.15)),
    "FTMUSDT-006": ("I-03", lambda: V.i03("FTMUSDT-006", "short"),
                    "ritorno dopo un rialzo estremo di 3 ore",
                    {"condizione": "z(3 ore) > +3, dev. std su 720 barre", "stop": "2 ATR(24)", "target": None, "uscita": "a tempo dopo 6 barre"},
                    (-0.15, 0.10)),
    "FTMUSDT-007": ("I-04", lambda: V.i04("FTMUSDT-007", "short"),
                    "funding estremo positivo: long affollati che si sciolgono",
                    {"condizione": "funding > 0,0001 e >= 90o percentile delle ultime 270 settlement", "stop": "2 ATR(21)",
                     "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.15, 0.10)),
    "FTMUSDT-008": ("I-04", lambda: V.i04("FTMUSDT-008", "long"),
                    "funding estremo negativo: short affollati che si sciolgono",
                    {"condizione": "funding < 0 e <= 10o percentile delle ultime 270 settlement", "stop": "2 ATR(21)",
                     "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.10, 0.15)),
    "FTMUSDT-009": ("I-05", lambda: V.i05("FTMUSDT-009"),
                    "rendimenti del lunedi' piu' alti",
                    {"condizione": "la barra di segnale e' una domenica (ingresso lunedi' 00:00 UTC)", "stop": "2 ATR(14)",
                     "target": None, "uscita": "a tempo dopo 1 barra"},
                    (-0.10, 0.10)),
    "FTMUSDT-010": ("I-06", lambda: V.i06("FTMUSDT-010", "long"),
                    "rottura di volatilita' della giornata: apertura + 0,5 range di ieri, fino a fine giornata",
                    {"condizione": "prima chiusura del giorno UTC sopra apertura + 0,5 x range di ieri, non alle 23:00",
                     "stop": "2 ATR(24)", "target": None, "uscita": "alla chiusura della barra delle 23:00"},
                    (-0.15, 0.10)),
    "FTMUSDT-011": ("I-06", lambda: V.i06("FTMUSDT-011", "short"),
                    "rottura di volatilita' della giornata verso il basso",
                    {"condizione": "prima chiusura del giorno UTC sotto apertura - 0,5 x range di ieri, non alle 23:00",
                     "stop": "2 ATR(24)", "target": None, "uscita": "alla chiusura della barra delle 23:00"},
                    (-0.15, 0.10)),
    "FTMUSDT-012": ("I-07", lambda: V.i07("FTMUSDT-012", "long"),
                    "ritorno di breve dentro il rialzo: RSI(2) < 10 sopra la media di 200",
                    {"condizione": "close > media(200) e RSI(2) < 10", "stop": "3 ATR(20)", "target": None,
                     "uscita": "close > media(5)"},
                    (-0.10, 0.15)),
    "FTMUSDT-013": ("I-07", lambda: V.i07("FTMUSDT-013", "short"),
                    "ritorno di breve dentro il ribasso: RSI(2) > 90 sotto la media di 200",
                    {"condizione": "close < media(200) e RSI(2) > 90", "stop": "3 ATR(20)", "target": None,
                     "uscita": "close < media(5)"},
                    (-0.10, 0.15)),
    "FTMUSDT-014": ("I-08", lambda: V.i08("FTMUSDT-014", "long"),
                    "BTC guida FTM: dopo un salto di BTC, FTM rimasto indietro recupera",
                    {"condizione": "rendimento BTC nella barra > 2 dev. std (720 barre) e rendimento FTM < BTC",
                     "stop": "2 ATR(24)", "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.10, 0.10)),
    "FTMUSDT-015": ("I-08", lambda: V.i08("FTMUSDT-015", "short"),
                    "BTC guida FTM: dopo un crollo di BTC, FTM rimasto indietro scende",
                    {"condizione": "rendimento BTC nella barra < -2 dev. std (720 barre) e rendimento FTM > BTC",
                     "stop": "2 ATR(24)", "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.10, 0.10)),
    "FTMUSDT-016": ("I-09", lambda: V.i09("FTMUSDT-016", "long"),
                    "compressione delle bande e uscita verso l'alto: la volatilita' si espande nella direzione della rottura",
                    {"condizione": "larghezza bande(i-1) <= 20o percentile di 120 barre e close > banda alta",
                     "stop": "2 ATR(20)", "target": None, "uscita": "close < media(20)"},
                    (-0.15, 0.15)),
    "FTMUSDT-017": ("I-09", lambda: V.i09("FTMUSDT-017", "short"),
                    "compressione delle bande e uscita verso il basso",
                    {"condizione": "larghezza bande(i-1) <= 20o percentile di 120 barre e close < banda bassa",
                     "stop": "2 ATR(20)", "target": None, "uscita": "close > media(20)"},
                    (-0.15, 0.15)),
    "FTMUSDT-018": ("I-10", lambda: V.i10("FTMUSDT-018", "short"),
                    "premio estremo del perpetuo sul mark: il perpetuo torna verso il riferimento",
                    {"condizione": "close last / close mark - 1 > 0 e >= 99o percentile di 720 barre", "stop": "2 ATR(24)",
                     "target": None, "uscita": "a tempo dopo 4 barre"},
                    (-0.15, 0.10)),
    "FTMUSDT-019": ("I-10", lambda: V.i10("FTMUSDT-019", "long"),
                    "sconto estremo del perpetuo sul mark: il perpetuo torna verso il riferimento",
                    {"condizione": "close last / close mark - 1 < 0 e <= 1o percentile di 720 barre", "stop": "2 ATR(24)",
                     "target": None, "uscita": "a tempo dopo 4 barre"},
                    (-0.10, 0.15)),
    "FTMUSDT-020": ("I-11", lambda: V.i11("FTMUSDT-020", "long"),
                    "prima mezz'ora positiva -> ultima mezz'ora positiva (giornata UTC)",
                    {"condizione": "barra delle 23:00 e close/open della barra 00:00 dello stesso giorno > 1", "stop": "2 ATR(48)",
                     "target": None, "uscita": "a tempo dopo 1 barra"},
                    (-0.20, 0.05)),
    "FTMUSDT-021": ("I-11", lambda: V.i11("FTMUSDT-021", "short"),
                    "prima mezz'ora negativa -> ultima mezz'ora negativa (giornata UTC)",
                    {"condizione": "barra delle 23:00 e close/open della barra 00:00 dello stesso giorno < 1", "stop": "2 ATR(48)",
                     "target": None, "uscita": "a tempo dopo 1 barra"},
                    (-0.20, 0.05)),
    "FTMUSDT-022": ("I-12", lambda: V.i12("FTMUSDT-022"),
                    "rendimento per rischio piu' alto con volatilita' bassa",
                    {"condizione": "dev. std rendimenti 30 giorni < sua mediana 180 giorni", "stop": "2,5 ATR(14)",
                     "target": None, "uscita": "a tempo dopo 5 barre"},
                    (-0.15, 0.15)),
    "FTMUSDT-023": ("I-13", lambda: V.i13("FTMUSDT-023", "long"),
                    "incrocio verso l'alto delle medie 10/50: inizio di un trend",
                    {"condizione": "media(10) incrocia sopra media(50)", "stop": "3 ATR(20)", "target": None,
                     "uscita": "media(10) < media(50)"},
                    (-0.15, 0.20)),
    "FTMUSDT-024": ("I-13", lambda: V.i13("FTMUSDT-024", "short"),
                    "incrocio verso il basso delle medie 10/50: inizio di un trend",
                    {"condizione": "media(10) incrocia sotto media(50)", "stop": "3 ATR(20)", "target": None,
                     "uscita": "media(10) > media(50)"},
                    (-0.15, 0.20)),
    "FTMUSDT-025": ("I-14", lambda: V.i14("FTMUSDT-025"),
                    "calo giornaliero con volume alto (vendita forzata) che torna indietro",
                    {"condizione": "rendimento del giorno < -1 dev. std (60 g) e volume > 1,5 x media dei 30 giorni precedenti",
                     "stop": "2 ATR(14)", "target": None, "uscita": "a tempo dopo 2 barre"},
                    (-0.10, 0.20)),
    "FTMUSDT-026": ("I-02", lambda: V.i02("FTMUSDT-026", "long", "2h"),
                    "rottura del massimo di 20 barre a 2 ore (allentamento dello scarto FTMUSDT-003)",
                    {"condizione": "close > max(high 20 barre precedenti)", "stop": "2 ATR(20)", "target": None,
                     "uscita": "close < min(low 10 barre precedenti)"},
                    (-0.15, 0.15)),
    "FTMUSDT-027": ("I-02", lambda: V.i02("FTMUSDT-027", "short", "2h"),
                    "rottura del minimo di 20 barre a 2 ore (allentamento dello scarto FTMUSDT-004)",
                    {"condizione": "close < min(low 20 barre precedenti)", "stop": "2 ATR(20)", "target": None,
                     "uscita": "close > max(high 10 barre precedenti)"},
                    (-0.15, 0.15)),
    "FTMUSDT-028": ("I-09", lambda: V.i09("FTMUSDT-028", "long", "2h"),
                    "compressione delle bande e uscita verso l'alto, a 2 ore (allentamento dello scarto FTMUSDT-016)",
                    {"condizione": "larghezza bande(i-1) <= 20o percentile di 120 barre e close > banda alta",
                     "stop": "2 ATR(20)", "target": None, "uscita": "close < media(20)"},
                    (-0.15, 0.15)),
    "FTMUSDT-029": ("I-09", lambda: V.i09("FTMUSDT-029", "short", "2h"),
                    "compressione delle bande e uscita verso il basso, a 2 ore (allentamento dello scarto FTMUSDT-017)",
                    {"condizione": "larghezza bande(i-1) <= 20o percentile di 120 barre e close < banda bassa",
                     "stop": "2 ATR(20)", "target": None, "uscita": "close > media(20)"},
                    (-0.15, 0.15)),
    "FTMUSDT-030": ("I-15", lambda: V.i15("FTMUSDT-030", "long"),
                    "attraversamento verso l'alto di un numero tondo: scattano gli stop degli short (cascata)",
                    {"condizione": "close supera il primo multiplo di 10^(floor(log10 close(-1))-1) sopra close(-1)",
                     "stop": "2 ATR(24)", "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.15, 0.10)),
    "FTMUSDT-031": ("I-15", lambda: V.i15("FTMUSDT-031", "short"),
                    "attraversamento verso il basso di un numero tondo: scattano gli stop dei long (cascata)",
                    {"condizione": "close scende al primo multiplo di 10^(floor(log10 close(-1))-1) sotto close(-1)",
                     "stop": "2 ATR(24)", "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.15, 0.10)),
    "FTMUSDT-032": ("I-13", lambda: V.i13("FTMUSDT-032", "long", "2h"),
                    "incrocio verso l'alto delle medie 10/50 a 2 ore (allentamento dello scarto FTMUSDT-023)",
                    {"condizione": "media(10) incrocia sopra media(50)", "stop": "3 ATR(20)", "target": None,
                     "uscita": "media(10) < media(50)"},
                    (-0.15, 0.20)),
    "FTMUSDT-033": ("I-13", lambda: V.i13("FTMUSDT-033", "short", "2h"),
                    "incrocio verso il basso delle medie 10/50 a 2 ore (allentamento dello scarto FTMUSDT-024)",
                    {"condizione": "media(10) incrocia sotto media(50)", "stop": "3 ATR(20)", "target": None,
                     "uscita": "media(10) > media(50)"},
                    (-0.15, 0.20)),
    "FTMUSDT-034": ("I-14", lambda: V.i14("FTMUSDT-034", "4h"),
                    "calo a 4 ore con volume alto che torna indietro (allentamento dello scarto FTMUSDT-025)",
                    {"condizione": "rendimento della barra < -1 dev. std (60 barre) e volume > 1,5 x media delle 30 barre precedenti",
                     "stop": "2 ATR(14)", "target": None, "uscita": "a tempo dopo 2 barre"},
                    (-0.10, 0.20)),
    # --- ritocchi (regola 6) ---
    "FTMUSDT-035": ("I-01", lambda: V.i01("FTMUSDT-035", "short", 7),
                    "momento di 1 settimana: dopo 7 giorni in ribasso il ribasso continua",
                    {"condizione": "close/close(-7) - 1 < 0", "stop": "2,5 ATR(14)", "target": None, "uscita": "a tempo dopo 5 barre"},
                    (-0.10, 0.15),
                    {"famiglia": "FTMUSDT-002", "ritocco_di": "FTMUSDT-002",
                     "cosa_cambia": "finestra del rendimento passato da 14 a 7 giorni. Perche': lo studio dei fallimenti di "
                                    "FTMUSDT-002 non mostra un fallimento sistematico da filtrare (il regime non lo spiega, nota "
                                    "FTMUSDT-N009); la fonte (Liu, Tsyvinski) da' l'effetto da 1 a 4 settimane e quello a 1 "
                                    "settimana e' il piu' vicino alla tenuta di 5 giorni. Si prova l'altro estremo dell'orizzonte "
                                    "della fonte invece di stringere filtri sui trade visti",
                     "previsione_extra": "differenza piccola rispetto a FTMUSDT-002; la finestra corta cambia segno piu' spesso"}),
    "FTMUSDT-036": ("I-01", lambda: V.i01("FTMUSDT-036", "short", 14, 3),
                    "momento di 2 settimane, short, tenuta piu' corta",
                    {"condizione": "close/close(-14) - 1 < 0", "stop": "2,5 ATR(14)", "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.10, 0.15),
                    {"famiglia": "FTMUSDT-002", "ritocco_di": "FTMUSDT-002",
                     "cosa_cambia": "uscita a tempo da 5 a 3 barre. Perche': nello studio dei fallimenti di FTMUSDT-002 (nota "
                                    "FTMUSDT-N009) le uscite a tempo valgono in media +0,145 R e i 7 stop -1 R ciascuno, arrivati "
                                    "durante la tenuta (rimbalzi violenti contro lo short); una tenuta piu' corta riduce "
                                    "l'esposizione a quei rimbalzi. Secondo ritocco della famiglia FTMUSDT-002, prima nell'ordine "
                                    "(t contro la (b) 1,60)",
                     "previsione_extra": "meno stop, R medio simile o un po' piu' basso; nessuna garanzia di battere la (b)"}),
    "FTMUSDT-037": ("I-01", lambda: V.i01("FTMUSDT-037", "short", 14, 3, 0.10),
                    "momento di 2 settimane, short, solo dopo ribassi di 14 giorni oltre il 10%",
                    {"condizione": "close/close(-14) - 1 < -0,10", "stop": "2,5 ATR(14)", "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.10, 0.20),
                    {"famiglia": "FTMUSDT-002", "ritocco_di": "FTMUSDT-036",
                     "cosa_cambia": "soglia del rendimento di 14 giorni da 0 a -10%. Perche': FTMUSDT-036 batte la (b) ma non la "
                                    "(a) (t 1,47): la condizione 'rendimento negativo' vale meta' dei giorni e distingue poco "
                                    "dall'entrare sempre. La sotto-domanda scritta in ipotesi.md prima dei test ('vale di piu' "
                                    "quando il movimento delle 14 giornate e' grande?') dice dove guardare; -10% e' circa mezza "
                                    "deviazione standard di 14 giorni di FTM, scelta senza guardare la distribuzione dei trade. "
                                    "Lo studio dei fallimenti (2021 negativo in entrambi i semestri, regime che non spiega) non "
                                    "da' un filtro migliore. Terzo ritocco della famiglia, primo nell'ordine (t contro la (b) 2,22)",
                     "previsione_extra": "meno trade (rischio di scarto sotto 70); R medio piu' alto se il meccanismo e' il "
                                         "momento, uguale se e' solo il ribasso del 2022"}),
    "FTMUSDT-038": ("I-01", lambda: V.i01("FTMUSDT-038", "short", 28, 3),
                    "momento di 4 settimane, short, tenuta 3 giorni",
                    {"condizione": "close/close(-28) - 1 < 0", "stop": "2,5 ATR(14)", "target": None, "uscita": "a tempo dopo 3 barre"},
                    (-0.10, 0.15),
                    {"famiglia": "FTMUSDT-002", "ritocco_di": "FTMUSDT-036",
                     "cosa_cambia": "finestra del rendimento passato da 14 a 28 giorni (tenuta 3 come FTMUSDT-036). Perche': "
                                    "FTMUSDT-036 resta prima nell'ordine (t contro la (b) 2,22); la soglia piu' severa "
                                    "(FTMUSDT-037) e la finestra di 7 giorni (FTMUSDT-035) non hanno aiutato; resta l'altro "
                                    "estremo dell'orizzonte della fonte (4 settimane), che segue trend piu' lunghi e cambia "
                                    "segno meno spesso. Quarto ritocco della famiglia, ultima variante del budget",
                     "previsione_extra": "simile a FTMUSDT-036; se il vantaggio e' il ribasso del 2022, R positivo solo nel 2022"}),
}
