"""Le registrazioni delle varianti (dati del log scritti PRIMA del test), da ipotesi.md.

Le previsioni sono al netto dei costi. Costo di un giro (commissione 0,05% + slippage
0,01% per lato, andata e ritorno) = 0,12% del nozionale, cioe' in R circa 0,12% / distanza
dello stop: 0,02 R con stop al 6%, 0,024 R al 5%, circa 0,04 R con 2 ATR a 4 ore (circa 3%),
0,12 R con stop all'1%.
"""

CRITERIO = ("batte nettamente la baseline (a) e la baseline (b) con contro_baseline "
            "e R medio dopo i costi > 0 (sezione 8, Fase 2)")

REGISTRO = {
    "V01": dict(idea="I-01", fonte="Moskowitz, Ooi, Pedersen, «Time series momentum», Journal of Financial Economics 104(2), maggio 2012; Liu, Tsyvinski, «Risks and Returns of Cryptocurrency», NBER WP 24877, agosto 2018",
                meccanismo="momentum a serie storica: rendimento di 7 giorni positivo -> long per 7 giorni",
                parametri={"rendimento_barre": 7, "tenuta_barre": 7, "stop_pct": 0.06},
                previsione={"testo": "R medio fra 0 e +0,15; non batte nettamente la (b) (t sotto la soglia)", "r_min": 0.0, "r_max": 0.15, "netta_b": False}),
    "V02": dict(idea="I-01", fonte="come V01",
                meccanismo="momentum a serie storica: rendimento di 7 giorni negativo -> short per 7 giorni",
                parametri={"rendimento_barre": 7, "tenuta_barre": 7, "stop_pct": 0.06},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V03": dict(idea="I-02", fonte="Curtis M. Faith, «Way of the Turtle», McGraw-Hill, 2007",
                meccanismo="rottura del massimo di 20 barre, uscita sul minimo di 10, stop 2 ATR(20)",
                parametri={"canale_ingresso": 20, "canale_uscita": 10, "atr": 20, "stop_atr": 2.0},
                previsione={"testo": "R medio fra 0 e +0,15; non batte nettamente la (b)", "r_min": 0.0, "r_max": 0.15, "netta_b": False}),
    "V04": dict(idea="I-02", fonte="come V03",
                meccanismo="rottura del minimo di 20 barre (short), uscita sul massimo di 10, stop 2 ATR(20)",
                parametri={"canale_ingresso": 20, "canale_uscita": 10, "atr": 20, "stop_atr": 2.0},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V05": dict(idea="I-03", fonte="Caporale, Plastun, «Price overreactions in the cryptocurrency market», Journal of Economic Studies 46(5), 2019",
                meccanismo="barra a 4 ore oltre +2 deviazioni standard -> long per 6 barre (continuazione)",
                parametri={"soglia_sd": 2.0, "finestra_sd": 180, "tenuta_barre": 6, "stop_pct": 0.05},
                previsione={"testo": "R medio fra -0,05 e +0,05; non batte la (b)", "r_min": -0.05, "r_max": 0.05, "netta_b": False}),
    "V06": dict(idea="I-03", fonte="come V05",
                meccanismo="barra a 4 ore oltre -2 deviazioni standard -> long per 6 barre (rimbalzo)",
                parametri={"soglia_sd": 2.0, "finestra_sd": 180, "tenuta_barre": 6, "stop_pct": 0.05},
                previsione={"testo": "R medio fra -0,05 e +0,10; non batte la (b)", "r_min": -0.05, "r_max": 0.10, "netta_b": False}),
    "V07": dict(idea="I-04", fonte="Connors, Alvarez, «Short Term Trading Strategies That Work», TradingMarkets, 2008",
                meccanismo="RSI(2) < 10 sopra la SMA(200) -> long, uscita sopra la SMA(5), stop 3 ATR(14)",
                parametri={"rsi": 2, "soglia_rsi": 10, "sma_trend": 200, "sma_uscita": 5, "atr": 14, "stop_atr": 3.0},
                previsione={"testo": "R medio fra 0 e +0,10; non batte la (b)", "r_min": 0.0, "r_max": 0.10, "netta_b": False}),
    "V08": dict(idea="I-04", fonte="come V07",
                meccanismo="RSI(2) > 90 sotto la SMA(200) -> short, uscita sotto la SMA(5), stop 3 ATR(14)",
                parametri={"rsi": 2, "soglia_rsi": 90, "sma_trend": 200, "sma_uscita": 5, "atr": 14, "stop_atr": 3.0},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V09": dict(idea="I-05", fonte="Caporale, Plastun, «The day of the week effect in the cryptocurrency market», Finance Research Letters 31, dicembre 2019",
                meccanismo="long il lunedi' (UTC), un giorno",
                parametri={"giorno": "lunedi", "tenuta_barre": 1, "stop_pct": 0.05},
                previsione={"testo": "R medio fra -0,05 e +0,10; non batte la (b)", "r_min": -0.05, "r_max": 0.10, "netta_b": False}),
    "V10": dict(idea="I-06", fonte="Larry Williams, «Long-Term Secrets to Short-Term Trading», Wiley, 1999",
                meccanismo="close oltre apertura del giorno + 0,5 range di ieri -> long fino a fine giorno, stop all'apertura",
                parametri={"k_range": 0.5, "uscita": "chiusura della barra delle 23:00 UTC", "stop": "apertura del giorno"},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V11": dict(idea="I-06", fonte="come V10",
                meccanismo="close sotto apertura del giorno - 0,5 range di ieri -> short fino a fine giorno, stop all'apertura",
                parametri={"k_range": 0.5, "uscita": "chiusura della barra delle 23:00 UTC", "stop": "apertura del giorno"},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V12": dict(idea="I-07", fonte="John Bollinger, «Bollinger on Bollinger Bands», McGraw-Hill, 2001",
                meccanismo="compressione delle bande (minimo di 125 barre nelle ultime 10) e close sopra la banda superiore -> long",
                parametri={"bande": [20, 2.0], "minimo_larghezza_barre": 125, "compressione_recente_barre": 10, "atr": 20, "stop_atr": 2.0, "uscita": "close sotto la media di 20"},
                previsione={"testo": "R medio fra -0,10 e +0,10; non batte la (b)", "r_min": -0.10, "r_max": 0.10, "netta_b": False}),
    "V13": dict(idea="I-07", fonte="come V12",
                meccanismo="compressione delle bande e close sotto la banda inferiore -> short",
                parametri={"bande": [20, 2.0], "minimo_larghezza_barre": 125, "compressione_recente_barre": 10, "atr": 20, "stop_atr": 2.0, "uscita": "close sopra la media di 20"},
                previsione={"testo": "R medio fra -0,10 e +0,10; non batte la (b)", "r_min": -0.10, "r_max": 0.10, "netta_b": False}),
    "V14": dict(idea="I-08", fonte="He, Manela, Ross, von Wachter, «Fundamentals of Perpetual Futures», arXiv 2212.06888, dicembre 2022",
                meccanismo="ultimo funding >= 0,05% -> short per 24 ore",
                parametri={"soglia_funding": 0.0005, "tenuta_barre": 3, "stop_pct": 0.05},
                previsione={"testo": "R medio fra -0,10 e +0,10; non batte la (b)", "r_min": -0.10, "r_max": 0.10, "netta_b": False}),
    "V15": dict(idea="I-08", fonte="come V14",
                meccanismo="ultimo funding < 0 -> long per 24 ore",
                parametri={"soglia_funding": 0.0, "tenuta_barre": 3, "stop_pct": 0.05},
                previsione={"testo": "R medio fra 0 e +0,15; non batte la (b)", "r_min": 0.0, "r_max": 0.15, "netta_b": False}),
    "V16": dict(idea="I-09", fonte="Chordia, Subrahmanyam, «Order imbalance and individual stock returns: Theory and evidence», Journal of Financial Economics 72(3), 2004",
                meccanismo="squilibrio taker delle ultime 24 ore sopra il 90° percentile di 30 giorni -> long 24 ore",
                parametri={"finestra_squilibrio_barre": 6, "finestra_percentile_barre": 180, "percentile": 90, "atr": 14, "stop_atr": 2.0, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,05 e +0,05; non batte la (b)", "r_min": -0.05, "r_max": 0.05, "netta_b": False}),
    "V17": dict(idea="I-09", fonte="come V16",
                meccanismo="squilibrio taker delle ultime 24 ore sotto il 10° percentile di 30 giorni -> short 24 ore",
                parametri={"finestra_squilibrio_barre": 6, "finestra_percentile_barre": 180, "percentile": 10, "atr": 14, "stop_atr": 2.0, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,05 e +0,05; non batte la (b)", "r_min": -0.05, "r_max": 0.05, "netta_b": False}),
    "V18": dict(idea="I-10", fonte="Gao, Han, Li, Zhou, «Market intraday momentum», Journal of Financial Economics 129(2), agosto 2018",
                meccanismo="prima mezz'ora UTC in rialzo -> long sull'ultima mezz'ora",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1},
                previsione={"testo": "R medio fra -0,15 e 0 (i costi sono 0,12 R); non batte la (b)", "r_min": -0.15, "r_max": 0.0, "netta_b": False}),
    "V19": dict(idea="I-10", fonte="come V18",
                meccanismo="prima mezz'ora UTC in ribasso -> short sull'ultima mezz'ora",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1},
                previsione={"testo": "R medio fra -0,15 e 0; non batte la (b)", "r_min": -0.15, "r_max": 0.0, "netta_b": False}),
    "V20": dict(idea="I-11", fonte="Carol L. Osler, «Currency Orders and Exchange Rate Dynamics: An Explanation for the Predictive Success of Technical Analysis», Journal of Finance 58(5), ottobre 2003",
                meccanismo="close orario sopra un multiplo di 1.000 superato -> long 4 ore, stop 1% sotto il livello",
                parametri={"passo_livelli": 1000, "stop": "K x 0,99", "tenuta_barre": 4},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V21": dict(idea="I-11", fonte="come V20",
                meccanismo="close orario sotto un multiplo di 1.000 superato al ribasso -> short 4 ore, stop 1% sopra il livello",
                parametri={"passo_livelli": 1000, "stop": "K x 1,01", "tenuta_barre": 4},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V22": dict(idea="I-12", fonte="Steve Nison, «Japanese Candlestick Charting Techniques», New York Institute of Finance, 1991",
                meccanismo="martello dopo un ribasso di 6 barre -> long 6 barre, stop al low del martello",
                parametri={"ombra_min_corpi": 2.0, "ombra_opposta_max_range": 0.1, "ribasso_barre": 6, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V23": dict(idea="I-12", fonte="come V22",
                meccanismo="stella cadente dopo un rialzo di 6 barre -> short 6 barre, stop all'high",
                parametri={"ombra_min_corpi": 2.0, "ombra_opposta_max_range": 0.1, "rialzo_barre": 6, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V24": dict(idea="I-13", fonte="George, Hwang, «The 52-Week High and Momentum Investing», Journal of Finance 59(5), ottobre 2004",
                meccanismo="close entro il 5% dal massimo di 365 giorni -> long 5 giorni",
                parametri={"vicinanza": 0.95, "finestra_barre": 365, "tenuta_barre": 5, "stop_pct": 0.06},
                previsione={"testo": "R medio fra 0 e +0,10; non batte la (b)", "r_min": 0.0, "r_max": 0.10, "netta_b": False}),
    "V25": dict(idea="I-14", fonte="Toby Crabel, «Day Trading with Short Term Price Patterns and Opening Range Breakout», Traders Press, 1990",
                meccanismo="ieri NR7; prima chiusura oraria oltre il massimo di ieri -> long fino a fine giorno, stop al minimo di ieri",
                parametri={"giorni_nr": 7, "uscita": "chiusura della barra delle 23:00 UTC", "stop": "minimo di ieri"},
                previsione={"testo": "R medio fra -0,05 e +0,15; non batte la (b)", "r_min": -0.05, "r_max": 0.15, "netta_b": False}),
    "V26": dict(idea="I-14", fonte="come V25",
                meccanismo="ieri NR7; prima chiusura oraria sotto il minimo di ieri -> short fino a fine giorno, stop al massimo di ieri",
                parametri={"giorni_nr": 7, "uscita": "chiusura della barra delle 23:00 UTC", "stop": "massimo di ieri"},
                previsione={"testo": "R medio fra -0,05 e +0,15; non batte la (b)", "r_min": -0.05, "r_max": 0.15, "netta_b": False}),
    "V27": dict(idea="I-15", fonte="Henry O. Pruden, «The Three Skills of Top Trading», Wiley, 2007 (metodo di Wyckoff)",
                meccanismo="low sotto il minimo di 20 barre e close sopra -> long 6 barre, stop sotto il low",
                parametri={"canale_barre": 20, "stop": "low x 0,999", "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,10 e +0,10; non batte la (b)", "r_min": -0.10, "r_max": 0.10, "netta_b": False}),
    "V28": dict(idea="I-15", fonte="come V27",
                meccanismo="high sopra il massimo di 20 barre e close sotto -> short 6 barre, stop sopra l'high",
                parametri={"canale_barre": 20, "stop": "high x 1,001", "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,10 e +0,10; non batte la (b)", "r_min": -0.10, "r_max": 0.10, "netta_b": False}),
    "V29": dict(idea="I-16", fonte="Brock, Lakonishok, LeBaron, «Simple Technical Trading Rules and the Stochastic Properties of Stock Returns», Journal of Finance 47(5), dicembre 1992",
                meccanismo="close supera 1,01 x SMA(50) -> long finche' close < 0,99 x SMA(50), stop 3 ATR(14)",
                parametri={"sma": 50, "banda": 0.01, "atr": 14, "stop_atr": 3.0},
                previsione={"testo": "R medio fra 0 e +0,20; non batte la (b)", "r_min": 0.0, "r_max": 0.20, "netta_b": False}),
    "V30": dict(idea="I-17", fonte="Gervais, Kaniel, Mingelgrin, «The High-Volume Return Premium», Journal of Finance 56(3), giugno 2001",
                meccanismo="volume della barra il piu' alto di 50 -> long 6 barre, stop 2 ATR(14)",
                parametri={"finestra_volume_barre": 50, "atr": 14, "stop_atr": 2.0, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V31": dict(idea="I-10", fonte="come V18 (ritocco di V19)", ritocco_di="V19", famiglia="V19",
                meccanismo="come V19 piu' il filtro: close delle 23:30 sotto l'apertura del giorno (giornata in calo)",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1, "filtro": "close < apertura del giorno"},
                cambia="aggiunge un filtro nato dallo studio dei fallimenti (N010): V19 perde di piu' nei giorni saliti forte (quartile alto del rendimento della giornata, R -0,16)",
                previsione={"testo": "R medio fra -0,08 e 0: il lordo di V19 (+0,045 R) e' un terzo dei costi (0,12 R); non candidato", "r_min": -0.08, "r_max": 0.0, "netta_b": False}),
    "V32": dict(idea="I-10", fonte="come V18 (ritocco di V31)", ritocco_di="V31", famiglia="V19",
                meccanismo="come V31 piu' il filtro: volatilita' di 20 giorni <= mediana dei 365 giorni prima",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1, "filtro_giornata": "close < apertura del giorno", "volatilita_barre": 960, "mediana_giorni": 365},
                cambia="aggiunge un filtro nato dallo studio dei fallimenti (N011): in V19 e in V31 il quartile piu' volatile e' il peggiore (-0,161 e -0,119)",
                previsione={"testo": "R medio fra -0,05 e +0,03; non candidato (trade intorno a 100, metà dei quali nel riscaldamento perduto)", "r_min": -0.05, "r_max": 0.03, "netta_b": False}),
    "V33": dict(idea="I-10", fonte="come V18 (ritocco di V31)", ritocco_di="V31", famiglia="V19",
                meccanismo="come V31 piu' il filtro: segnale solo il sabato e la domenica (UTC)",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1, "filtro_giornata": "close < apertura del giorno", "giorni": ["sabato", "domenica"]},
                cambia="aggiunge un filtro visto nello studio dei fallimenti di V31 (N012): R per giorno della settimana, sabato -0,013, domenica +0,136, gli altri tutti negativi. Filtro trovato guardando i dati, senza un meccanismo forte (liquidita' del fine settimana): il piu' esposto al caso",
                previsione={"testo": "R medio fra -0,02 e +0,10; batte la (b) ma e' quasi certamente fortuna (filtro scelto sui dati)", "r_min": -0.02, "r_max": 0.10, "netta_b": True}),
    "V34": dict(idea="I-10", fonte="come V18 (ritocco di V31)", ritocco_di="V31", famiglia="V19",
                meccanismo="come V31 piu' i filtri di volatilita' bassa (V32) e fine settimana (V33)",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1, "filtro_giornata": "close < apertura del giorno", "volatilita_barre": 960, "mediana_giorni": 365, "giorni": ["sabato", "domenica"]},
                cambia="unisce i due filtri nati dai fallimenti di V19 e V31 (N011, N012)",
                previsione={"testo": "probabilmente sotto i 70 trade (scarto); se testata, R medio fra -0,05 e +0,10", "r_min": -0.05, "r_max": 0.10, "netta_b": False}),
    "V35": dict(idea="I-10", fonte="come V18 (ritocco di V31)", ritocco_di="V31", famiglia="V19",
                meccanismo="come V31 piu' il filtro: volatilita' di 20 giorni <= 75° percentile dei 365 giorni prima",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1, "filtro_giornata": "close < apertura del giorno", "volatilita_barre": 960, "percentile_giorni": 365, "percentile": 75},
                cambia="soglia del filtro di volatilita' (nato dai fallimenti, N011) meno stretta: dalla mediana al 75° percentile; quinto e ultimo ritocco della famiglia V19",
                previsione={"testo": "R medio fra -0,04 e +0,01; non batte nettamente la (b)", "r_min": -0.04, "r_max": 0.01, "netta_b": False}),
    "V36": dict(idea="I-15", fonte="come V27 (ritocco di V28)", ritocco_di="V28", famiglia="V28",
                meccanismo="come V28 piu' il filtro: volatilita' delle ultime 960 barre sopra la sua mediana delle 2.190 barre precedenti",
                parametri={"canale_barre": 20, "stop": "high x 1,001", "tenuta_barre": 6, "volatilita_barre": 960, "mediana_barre": 2190},
                cambia="aggiunge un filtro nato dallo studio dei fallimenti (N014): R di V28 per quartile di volatilita' -0,194; -0,087; +0,042; +0,244",
                previsione={"testo": "R medio fra -0,05 e +0,15; non batte nettamente la (b) (pochi trade dopo il riscaldamento)", "r_min": -0.05, "r_max": 0.15, "netta_b": False}),
    "V37": dict(idea="I-15", fonte="come V27 (ritocco di V28)", ritocco_di="V28", famiglia="V28",
                meccanismo="come V36 ma con la mediana della volatilita' sulle 1.095 barre precedenti (182 giorni)",
                parametri={"canale_barre": 20, "stop": "high x 1,001", "tenuta_barre": 6, "volatilita_barre": 960, "mediana_barre": 1095},
                cambia="V36 e' rimasta sotto i trade minimi (67) per il riscaldamento: finestra della mediana dimezzata, filtro nato dai fallimenti (N014)",
                previsione={"testo": "R medio fra -0,05 e +0,15; non batte nettamente la (b)", "r_min": -0.05, "r_max": 0.15, "netta_b": False}),
}
