"""Le registrazioni delle varianti (dati del log scritti PRIMA del test), da ipotesi.md.

Le previsioni sono al netto dei costi. Costo di un giro (commissione 0,05% + slippage
0,01% per lato, andata e ritorno) = 0,12% del nozionale, cioe' in R circa 0,12% / distanza
dello stop: 0,02 R con stop al 6%, 0,024 R al 5%, circa 0,04 R con 2 ATR a 4 ore (circa 3%),
0,12 R con stop all'1%.
"""

CRITERIO = ("batte nettamente la baseline (a) e la baseline (b) con contro_baseline "
            "e R medio dopo i costi > 0 (sezione 8, Fase 2)")

REGISTRO = {
    "V01": dict(idea="I-01", fonte="Moskowitz, Ooi, Pedersen, «Time series momentum», Journal of Financial Economics 104(2), maggio 2012; Liu, Tsyvinski, «Risks and Returns of Cryptocurrency», NBER WP 24877, agosto 2018",
                meccanismo="momentum a serie storica: rendimento di 7 giorni positivo -> long per 7 giorni",
                parametri={"rendimento_barre": 7, "tenuta_barre": 7, "stop_pct": 0.06},
                previsione={"testo": "R medio fra 0 e +0,15; non batte nettamente la (b) (t sotto la soglia)", "r_min": 0.0, "r_max": 0.15, "netta_b": False}),
    "V02": dict(idea="I-01", fonte="come V01",
                meccanismo="momentum a serie storica: rendimento di 7 giorni negativo -> short per 7 giorni",
                parametri={"rendimento_barre": 7, "tenuta_barre": 7, "stop_pct": 0.06},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V03": dict(idea="I-02", fonte="Curtis M. Faith, «Way of the Turtle», McGraw-Hill, 2007",
                meccanismo="rottura del massimo di 20 barre, uscita sul minimo di 10, stop 2 ATR(20)",
                parametri={"canale_ingresso": 20, "canale_uscita": 10, "atr": 20, "stop_atr": 2.0},
                previsione={"testo": "R medio fra 0 e +0,15; non batte nettamente la (b)", "r_min": 0.0, "r_max": 0.15, "netta_b": False}),
    "V04": dict(idea="I-02", fonte="come V03",
                meccanismo="rottura del minimo di 20 barre (short), uscita sul massimo di 10, stop 2 ATR(20)",
                parametri={"canale_ingresso": 20, "canale_uscita": 10, "atr": 20, "stop_atr": 2.0},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V05": dict(idea="I-03", fonte="Caporale, Plastun, «Price overreactions in the cryptocurrency market», Journal of Economic Studies 46(5), 2019",
                meccanismo="barra a 4 ore oltre +2 deviazioni standard -> long per 6 barre (continuazione)",
                parametri={"soglia_sd": 2.0, "finestra_sd": 180, "tenuta_barre": 6, "stop_pct": 0.05},
                previsione={"testo": "R medio fra -0,05 e +0,05; non batte la (b)", "r_min": -0.05, "r_max": 0.05, "netta_b": False}),
    "V06": dict(idea="I-03", fonte="come V05",
                meccanismo="barra a 4 ore oltre -2 deviazioni standard -> long per 6 barre (rimbalzo)",
                parametri={"soglia_sd": 2.0, "finestra_sd": 180, "tenuta_barre": 6, "stop_pct": 0.05},
                previsione={"testo": "R medio fra -0,05 e +0,10; non batte la (b)", "r_min": -0.05, "r_max": 0.10, "netta_b": False}),
    "V07": dict(idea="I-04", fonte="Connors, Alvarez, «Short Term Trading Strategies That Work», TradingMarkets, 2008",
                meccanismo="RSI(2) < 10 sopra la SMA(200) -> long, uscita sopra la SMA(5), stop 3 ATR(14)",
                parametri={"rsi": 2, "soglia_rsi": 10, "sma_trend": 200, "sma_uscita": 5, "atr": 14, "stop_atr": 3.0},
                previsione={"testo": "R medio fra 0 e +0,10; non batte la (b)", "r_min": 0.0, "r_max": 0.10, "netta_b": False}),
    "V08": dict(idea="I-04", fonte="come V07",
                meccanismo="RSI(2) > 90 sotto la SMA(200) -> short, uscita sotto la SMA(5), stop 3 ATR(14)",
                parametri={"rsi": 2, "soglia_rsi": 90, "sma_trend": 200, "sma_uscita": 5, "atr": 14, "stop_atr": 3.0},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V09": dict(idea="I-05", fonte="Caporale, Plastun, «The day of the week effect in the cryptocurrency market», Finance Research Letters 31, dicembre 2019",
                meccanismo="long il lunedi' (UTC), un giorno",
                parametri={"giorno": "lunedi", "tenuta_barre": 1, "stop_pct": 0.05},
                previsione={"testo": "R medio fra -0,05 e +0,10; non batte la (b)", "r_min": -0.05, "r_max": 0.10, "netta_b": False}),
    "V10": dict(idea="I-06", fonte="Larry Williams, «Long-Term Secrets to Short-Term Trading», Wiley, 1999",
                meccanismo="close oltre apertura del giorno + 0,5 range di ieri -> long fino a fine giorno, stop all'apertura",
                parametri={"k_range": 0.5, "uscita": "chiusura della barra delle 23:00 UTC", "stop": "apertura del giorno"},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V11": dict(idea="I-06", fonte="come V10",
                meccanismo="close sotto apertura del giorno - 0,5 range di ieri -> short fino a fine giorno, stop all'apertura",
                parametri={"k_range": 0.5, "uscita": "chiusura della barra delle 23:00 UTC", "stop": "apertura del giorno"},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V12": dict(idea="I-07", fonte="John Bollinger, «Bollinger on Bollinger Bands», McGraw-Hill, 2001",
                meccanismo="compressione delle bande (minimo di 125 barre nelle ultime 10) e close sopra la banda superiore -> long",
                parametri={"bande": [20, 2.0], "minimo_larghezza_barre": 125, "compressione_recente_barre": 10, "atr": 20, "stop_atr": 2.0, "uscita": "close sotto la media di 20"},
                previsione={"testo": "R medio fra -0,10 e +0,10; non batte la (b)", "r_min": -0.10, "r_max": 0.10, "netta_b": False}),
    "V13": dict(idea="I-07", fonte="come V12",
                meccanismo="compressione delle bande e close sotto la banda inferiore -> short",
                parametri={"bande": [20, 2.0], "minimo_larghezza_barre": 125, "compressione_recente_barre": 10, "atr": 20, "stop_atr": 2.0, "uscita": "close sopra la media di 20"},
                previsione={"testo": "R medio fra -0,10 e +0,10; non batte la (b)", "r_min": -0.10, "r_max": 0.10, "netta_b": False}),
    "V14": dict(idea="I-08", fonte="He, Manela, Ross, von Wachter, «Fundamentals of Perpetual Futures», arXiv 2212.06888, dicembre 2022",
                meccanismo="ultimo funding >= 0,05% -> short per 24 ore",
                parametri={"soglia_funding": 0.0005, "tenuta_barre": 3, "stop_pct": 0.05},
                previsione={"testo": "R medio fra -0,10 e +0,10; non batte la (b)", "r_min": -0.10, "r_max": 0.10, "netta_b": False}),
    "V15": dict(idea="I-08", fonte="come V14",
                meccanismo="ultimo funding < 0 -> long per 24 ore",
                parametri={"soglia_funding": 0.0, "tenuta_barre": 3, "stop_pct": 0.05},
                previsione={"testo": "R medio fra 0 e +0,15; non batte la (b)", "r_min": 0.0, "r_max": 0.15, "netta_b": False}),
    "V16": dict(idea="I-09", fonte="Chordia, Subrahmanyam, «Order imbalance and individual stock returns: Theory and evidence», Journal of Financial Economics 72(3), 2004",
                meccanismo="squilibrio taker delle ultime 24 ore sopra il 90° percentile di 30 giorni -> long 24 ore",
                parametri={"finestra_squilibrio_barre": 6, "finestra_percentile_barre": 180, "percentile": 90, "atr": 14, "stop_atr": 2.0, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,05 e +0,05; non batte la (b)", "r_min": -0.05, "r_max": 0.05, "netta_b": False}),
    "V17": dict(idea="I-09", fonte="come V16",
                meccanismo="squilibrio taker delle ultime 24 ore sotto il 10° percentile di 30 giorni -> short 24 ore",
                parametri={"finestra_squilibrio_barre": 6, "finestra_percentile_barre": 180, "percentile": 10, "atr": 14, "stop_atr": 2.0, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,05 e +0,05; non batte la (b)", "r_min": -0.05, "r_max": 0.05, "netta_b": False}),
    "V18": dict(idea="I-10", fonte="Gao, Han, Li, Zhou, «Market intraday momentum», Journal of Financial Economics 129(2), agosto 2018",
                meccanismo="prima mezz'ora UTC in rialzo -> long sull'ultima mezz'ora",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1},
                previsione={"testo": "R medio fra -0,15 e 0 (i costi sono 0,12 R); non batte la (b)", "r_min": -0.15, "r_max": 0.0, "netta_b": False}),
    "V19": dict(idea="I-10", fonte="come V18",
                meccanismo="prima mezz'ora UTC in ribasso -> short sull'ultima mezz'ora",
                parametri={"stop_pct": 0.01, "tenuta_barre": 1},
                previsione={"testo": "R medio fra -0,15 e 0; non batte la (b)", "r_min": -0.15, "r_max": 0.0, "netta_b": False}),
    "V20": dict(idea="I-11", fonte="Carol L. Osler, «Currency Orders and Exchange Rate Dynamics: An Explanation for the Predictive Success of Technical Analysis», Journal of Finance 58(5), ottobre 2003",
                meccanismo="close orario sopra un multiplo di 1.000 superato -> long 4 ore, stop 1% sotto il livello",
                parametri={"passo_livelli": 1000, "stop": "K x 0,99", "tenuta_barre": 4},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V21": dict(idea="I-11", fonte="come V20",
                meccanismo="close orario sotto un multiplo di 1.000 superato al ribasso -> short 4 ore, stop 1% sopra il livello",
                parametri={"passo_livelli": 1000, "stop": "K x 1,01", "tenuta_barre": 4},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V22": dict(idea="I-12", fonte="Steve Nison, «Japanese Candlestick Charting Techniques», New York Institute of Finance, 1991",
                meccanismo="martello dopo un ribasso di 6 barre -> long 6 barre, stop al low del martello",
                parametri={"ombra_min_corpi": 2.0, "ombra_opposta_max_range": 0.1, "ribasso_barre": 6, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V23": dict(idea="I-12", fonte="come V22",
                meccanismo="stella cadente dopo un rialzo di 6 barre -> short 6 barre, stop all'high",
                parametri={"ombra_min_corpi": 2.0, "ombra_opposta_max_range": 0.1, "rialzo_barre": 6, "tenuta_barre": 6},
                previsione={"testo": "R medio fra -0,10 e +0,05; non batte la (b)", "r_min": -0.10, "r_max": 0.05, "netta_b": False}),
    "V24": dict(idea="I-13", fonte="George, Hwang, «The 52-Week High and Momentum Investing», Journal of Finance 59(5), ottobre 2004",
                meccanismo="close entro il 5% dal massimo di 365 giorni -> long 5 giorni",
                parametri={"vicinanza": 0.95, "finestra_barre": 365, "tenuta_barre": 5, "stop_pct": 0.06},
                previsione={"testo": "R medio fra 0 e +0,10; non batte la (b)", "r_min": 0.0, "r_max": 0.10, "netta_b": False}),
}
